### PR TITLE
allow docker builds since debian release and add instructions for using in a networked situation.

### PR DESCRIPTION
**Pull request by jeffrichards**

### CODE REVIEW

**Comment by juneeighteen** [comment]
@all-contributors please add @jeffrichards for finding and fixing a broken build

**Comment by juneeighteen** [comment]
https://github.com/all-contributors please add @jeffrichards for bug

**Comment by juneeighteen** [comment]
@all-contributors please add @jeffrichards for bug

**Comment by jeffrichards** [comment]
Closing in favor of PR #2

**Pull request closed without merging**
